#!/usr/bin/env bash
set -euo pipefail
repo="trietnguyenk16-nkt/Stock-Advisor"
gh label create "request" --repo "$repo" --description "User-requested implementation tracking" --color "1d76db" 2>/dev/null || true
gh label create "DONE" --repo "$repo" --description "Implemented and verified by the user" --color "0e8a16" 2>/dev/null || true
create_issue() {
  local title="$1"
  local body="$2"
  gh issue create --repo "$repo" --title "$title" --body "$body" --label "request"
}
create_issue "request-01: Watchlist hiển thị giá mua và giá bán vàng" $'## Mục tiêu\nBổ sung giá mua/giá bán cho SJC trong Watchlist.\n\n## Tiêu chí nghiệm thu\n- SJC hiển thị bid và ask bằng VND.\n- Hiển thị trạng thái thiếu dữ liệu rõ ràng khi nguồn không trả giá.\n- Có test provider và UI/API contract.'
create_issue "request-02: Chuẩn hóa biến động theo mốc ngày hôm trước" $'## Mục tiêu\nHiển thị tăng/giảm theo phần trăm và ghi rõ mốc so sánh.\n\n## Tiêu chí nghiệm thu\n- Có giá trị phần trăm tăng/giảm.\n- Ghi rõ mốc liền trước hoặc ngày hôm trước.\n- Không crash khi thiếu previous price.'
create_issue "request-03: Thêm cột nguồn dữ liệu trong Watchlist" $'## Mục tiêu\nCho người dùng biết từng giá được lấy từ nguồn nào.\n\n## Tiêu chí nghiệm thu\n- Cột Nguồn xuất hiện cho cổ phiếu, quỹ và vàng.\n- Có source name và link khi nguồn cung cấp URL.\n- Không hiển thị nguồn giả hoặc nguồn không xác định như đã xác minh.'
create_issue "request-04: Audit chi tiết từng tài sản trong Sync History" $'## Mục tiêu\nMỗi lần sync lưu mã, trường dữ liệu, timestamp, nguồn, giá trước/sau và thay đổi.\n\n## Tiêu chí nghiệm thu\n- Có bảng chi tiết additive-only trong Supabase.\n- History hiển thị từng tài sản và trạng thái thành công/lỗi.\n- Manual, cron và CLI dùng chung audit model.'
create_issue "request-05: Watchlist lọc ngày và so sánh giá lịch sử" $'## Mục tiêu\nCho phép chọn ngày, tải giá ngày đó, tô màu so sánh và reset.\n\n## Tiêu chí nghiệm thu\n- Mặc định ngày hiện tại.\n- Cột Giá ngày YYYY-MM-DD tự xuất hiện khi chọn ngày.\n- Giá thấp hơn hiện tại màu đỏ, cao hơn màu xanh, bằng màu vàng.\n- Không có dữ liệu hiển thị rõ; Reset xóa cột và về ngày hiện tại.'
create_issue "request-06: AI dùng giá hiện tại và tin kinh tế đáng tin cậy" $'## Mục tiêu\nAI phân tích dựa trên quote hiện tại có timestamp và tin từ nguồn đáng tin cậy.\n\n## Tiêu chí nghiệm thu\n- Payload AI chứa quote, thời điểm, nguồn và tin liên quan.\n- Không bịa dữ liệu hoặc dùng nguồn ngoài payload.\n- Kết quả có BUY/SELL/HOLD, giá tham chiếu, mục tiêu, lý do, rủi ro và confidence.'
create_issue "request-07: Ô Yêu cầu nối vào system prompt AI" $'## Mục tiêu\nThêm ô Yêu cầu để người dùng nhập mục tiêu như đầu tư dài hạn.\n\n## Tiêu chí nghiệm thu\n- Yêu cầu được truyền server-side và nối vào system prompt có giới hạn độ dài.\n- UI giải thích rõ cách dùng.\n- Lịch sử lưu yêu cầu đã dùng.'
create_issue "request-08: AI nhận diện ticker đơn lẻ trong ô Yêu cầu" $'## Mục tiêu\nNếu nhập chỉ ticker, AI chỉ phân tích ticker đó sau khi kiểm tra Watchlist.\n\n## Tiêu chí nghiệm thu\n- Ticker có trong Watchlist: chỉ một mã được gửi vào AI.\n- Ticker không có: báo thêm và đồng bộ trước khi gọi AI.\n- Không nhập ticker: phân tích toàn Watchlist.'
create_issue "request-09: Fix AI không có quote hợp lệ" $'## Mục tiêu\nKhông còn kết quả 0 tài sản khi mã có dữ liệu giá hiện tại.\n\n## Tiêu chí nghiệm thu\n- AI preflight lấy quote khi snapshot thiếu.\n- Quỹ và vàng dùng đúng provider.\n- UI hiển thị analyzed, skipped và lỗi cụ thể.'
create_issue "request-10: Fix tài sản mới không được cập nhật khi manual sync" $'## Mục tiêu\nMã vừa thêm phải được ghi vào tracked_assets và đồng bộ ngay.\n\n## Tiêu chí nghiệm thu\n- Manual sync đọc cùng watchlist với UI.\n- Snapshot và status của mã mới được cập nhật.\n- History có record cho mã mới.'
create_issue "request-11: Lưu lịch sử các lần tư vấn AI trong Supabase" $'## Mục tiêu\nLưu run AI, yêu cầu, model, phạm vi mã, kết quả và ngày tư vấn.\n\n## Tiêu chí nghiệm thu\n- Có bảng additive-only và migration/schema tương ứng.\n- History hiển thị các run AI.\n- Lưu cả failed/partial với thông báo lỗi.'
create_issue "request-12: Hiển thị hướng dẫn workflow dưới phân tích AI" $'## Mục tiêu\nGiải thích cách app xử lý yêu cầu AI.\n\n## Tiêu chí nghiệm thu\n- Nói rõ không nhập yêu cầu thì phân tích toàn Watchlist.\n- Nói rõ nhập ticker thì chỉ phân tích ticker đó.\n- Nói rõ phải thêm và đồng bộ trước khi phân tích.'
create_issue "request-13: Thay tagline dashboard bằng thông điệp có ý nghĩa" $'## Mục tiêu\nThay câu tagline chung bằng thông điệp mô tả giá trị Stock Advisor.\n\n## Tiêu chí nghiệm thu\n- Nội dung nói rõ theo dõi dữ liệu và hỗ trợ quyết định đầu tư.\n- Không dùng wording phóng đại hoặc cam kết lợi nhuận.'
create_issue "request-14: Kiểm tra notification và email digest" $'## Mục tiêu\nBảo đảm trạng thái cấu hình push và email được kiểm tra, hiển thị đúng.\n\n## Tiêu chí nghiệm thu\n- Push config báo thiếu VAPID rõ ràng hoặc hoạt động khi đủ secrets.\n- Email digest hiển thị lịch 18:00 hằng ngày và trạng thái gửi gần nhất.\n- Không báo sẵn sàng khi thiếu cấu hình bắt buộc.'
create_issue "request-15: Fix NAV chứng chỉ quỹ và fallback provider" $'## Mục tiêu\nDCDS, SSISCA, VCBF và các quỹ trong catalog phải lấy được NAV.\n\n## Tiêu chí nghiệm thu\n- Chuẩn hóa SSISCA thành SSI-SCA khi cần.\n- Loại bỏ NAV 0.00/NaN.\n- Manual sync, scheduled sync và quote endpoint dùng fallback CafeF đã xác minh.\n- Có test NAV thực tế/mocked contract và source metadata.'
