-- Stock Advisor: additive-only persistence for readable History run details.
-- Safe for a shared Supabase database: no DROP, DELETE, TRUNCATE or existing-column changes.

create schema if not exists stock_advisor;

create table if not exists stock_advisor.sync_run_assets (
  id bigint generated by default as identity primary key,
  run_key varchar(96) not null,
  asset_id bigint not null,
  ticker varchar(32) not null,
  display_name varchar(255) not null,
  status varchar(16) not null,
  previous_price numeric(20,6),
  price numeric(20,6),
  bid numeric(20,6),
  ask numeric(20,6),
  change_percent numeric(12,6),
  source_name varchar(128),
  source_url varchar(1024),
  as_of bigint,
  message text,
  created_at timestamptz not null default now(),
  unique(run_key, asset_id)
);

create index if not exists sync_run_assets_run_key_index
  on stock_advisor.sync_run_assets (run_key);

alter table stock_advisor.sync_runs
  add column if not exists summary_title text,
  add column if not exists detail_text text,
  add column if not exists details_json jsonb;

create table if not exists stock_advisor.ai_advice_runs (
  id bigint generated by default as identity primary key,
  run_key varchar(96) not null unique,
  workspace_key varchar(96) not null default 'owner',
  requested_ticker varchar(32),
  additional_requirement text,
  model varchar(64) not null,
  status varchar(16) not null,
  assets_requested integer not null default 0,
  assets_analyzed integer not null default 0,
  assets_skipped integer not null default 0,
  error_message text,
  summary_title text,
  detail_text text,
  response_json jsonb,
  started_at bigint not null,
  finished_at bigint,
  created_at timestamptz not null default now()
);

alter table stock_advisor.ai_advice_runs
  add column if not exists summary_title text,
  add column if not exists detail_text text;

create index if not exists ai_advice_runs_workspace_started_index
  on stock_advisor.ai_advice_runs (workspace_key, started_at desc);

-- Verification query:
-- select table_name, column_name
-- from information_schema.columns
-- where table_schema = 'stock_advisor'
--   and table_name in ('sync_runs', 'sync_run_assets', 'ai_advice_runs')
-- order by table_name, ordinal_position;
